--- !ditz.rubyforge.org,2008-03-06/project 
name: yodnsconf
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: yodnsconf
- !ditz.rubyforge.org,2008-03-06/component 
  name: yodnsconf-web
- !ditz.rubyforge.org,2008-03-06/component 
  name: yodnsconf-cli
releases: []

